### ISSUE TITLE
MD5

### ISSUE THREAD

**Issue by tegk** [geohot/minikeyvalue#15]
There is no requirement for a cryptographic hash to use, right?
Let us use a non cryptographic hash then like xxhash or murmur3 as they are much faster.

I am happy to send a PR in case we agree :-)

**Comment by geohot** [comment]
We already have this in use with MD5, so can't really change. Reason for the MD5 decision is I'm not sure speed is such a concern, and I know I can trust a cryptographic hash.

**Comment by tegk** [comment]
Ok, I understand.
